apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmjob-deployment
  labels:
    app: rmjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmjob
  template:
    metadata:
      labels:
        app: rmjob
    spec:
      containers:
      - name: rmjob
        image: uniquebiwas/test_remotejob:latest
        ports:
        - containerPort: 8000